fix: docker compose ci: use un-cached build, add API smoke test, add missing error exits (#5904)

diff --git a/.github/workflows/docker_compose_ci.yml b/.github/workflows/docker_compose_ci.yml
--- a/.github/workflows/docker_compose_ci.yml
+++ b/.github/workflows/docker_compose_ci.yml
@@ -32,8 +32,9 @@ jobs:
       - name: build
         shell: bash
         run: |
-          if ! docker compose build; then
+          if ! docker compose build --no-cache; then
             echo 'ERROR: docker compose build failed'
+            exit 1
           fi
 
       - name: dbinitcheck
@@ -57,6 +58,22 @@ jobs:
 
           if ! docker compose down; then
             echo 'ERROR: docker compose down failed'
+            exit 1
+          fi
+
+      - name: api-smoke-test
+        shell: bash
+        run: |
+          if ! docker compose up --wait api
+          then
+            echo 'ERROR: api did not start successfully. Logs:'
+            docker compose logs api
+            exit 1
+          fi
+
+          if ! docker compose down; then
+            echo 'ERROR: docker compose down failed'
+            exit 1
           fi
 
       - name: dbreadonlycheck
@@ -72,6 +89,7 @@ jobs:
 
           if ! docker compose down; then
             echo 'ERROR: docker compose down failed'
+            exit 1
           fi
 
       - name: sites-smoke-test
